apiVersion: v1
kind: Service
metadata:
  name: users-mongo
  labels:
    app: acmefit
    service: users-mongo
spec:
  ports:
    - port: 27017
      name: mongo-users
      protocol: TCP
  selector:
    app: acmefit
    service: users-mongo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-mongo
  labels:
    app: acmefit
    service: users-mongo
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: acmefit  # has to match .spec.template.metadata.labels
      service: users-mongo
  replicas: 1
  template:
    metadata:
      labels:
        app: acmefit  # has to match .spec.selector.matchLabels
        service: users-mongo
    spec:
      containers:
        - name: users-mongo
          image: mongo:4
          resources:
            {}
          ports:
            - name: users-mongo
              containerPort: 27017
              protocol: "TCP"
          env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: 'mongoadmin'
          - name: MONGO_INITDB_DATABASE
            value: 'acmefit'
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: users-mongo-pass
                key: password
          volumeMounts:
            - mountPath: /data/db
              name: mongodata
            - mountPath: /docker-entrypoint-initdb.d
              name: mongo-initdb
      volumes:
        # - name: mongodata
        #   emptyDir: {}
        - name: mongo-initdb
          configMap:
            name: users-initdb-config
        - name: mongodata
          persistentVolumeClaim:
            claimName: mongodata-users-mongo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodata-users-mongo
  namespace: acme-fitness
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: app
            operator: In
            values:
              - acmefit
          - key: service
            operator: In
            values:
              - users-mongo